### ISSUE TITLE
Support for Expo managed workflow

### ISSUE THREAD

**Issue by jay-jlm** [MoralisWeb3/react-moralis#112]
### Current Limitation

It appears to me that at least additional instructions are needed in order to be able to run a [Expo managed workflow](https://docs.expo.dev/introduction/managed-vs-bare/#managed-workflow) without compilation errors, if that's even possible at all.

### Feature / Enhancement Description

After configuring the code to run in RN environment in the following manner:

```JSX
import Moralis from "moralis/react-native";
import { MoralisProvider } from "react-moralis";

const getMoralis = () => Moralis

export default function App() {
  return (
    <MoralisProvider
      environment="native"
      getMoralis={getMoralis}
      appId="dxtPXb6rRSzQnIAcgIKScHS5sxrUI0dvmgO8xiQs"
      serverUrl="https://si9oaram1zec.usemoralis.com:2053/server">
```

I still get the following error when trying to run a newly created expo **managed** project:

```
[00:58:05] Android Bundling failed 15409ms
[00:58:05] Unable to resolve module events from D:\projects_2021\moralis\my-app\node_modules\moralis\lib\react-native\MoralisWeb3.js:  events could not be found within the project or in these directories:
[00:58:05]   node_modules\moralis\node_modules
[00:58:05]   node_modules
[00:58:05]
[00:58:05] If you are sure the module exists, try these steps:
[00:58:05]  1. Clear watchman watches: watchman watch-del-all
[00:58:05]  2. Delete node_modules and run yarn install
[00:58:05]  3. Reset Metro's cache: yarn start --reset-cache
[00:58:05]  4. Remove the cache: rm -rf /tmp/metro-*
[00:58:05]   167 | }
[00:58:05]   168 |
[00:58:05] > 169 | var EventEmitter = require('events');
[00:58:05]       |                             ^
[00:58:05]   170 |
[00:58:05]   171 | var EthereumEvents = {
[00:58:05]   172 |   CONNECT: 'connect',

```

### Alternatives / Workarounds

With additional configuration  based on [this repository](https://github.com/ethereum-boilerplate/ethereum-react-native-boilerplate)  it's possible to fix some dependency errors, however not there's at least one important difference in that managed workflow projects rely on `expo-crypto` instead of `react-native-crypto` .

### 3rd Party References

`expo-crypto` feature set support is described here: https://docs.expo.dev/versions/latest/sdk/crypto/
Expo support discussion thread: https://expo.canny.io/feature-requests/p/crypto-api
Moralis + RN boilerplate: https://github.com/ethereum-boilerplate/ethereum-react-native-boilerplate

**Comment by saricden** [comment]
@jay-jlm can you describe your workaround? I'm stuck on this as well.

**Comment by saricden** [comment]
I managed to get a VERY hacky fresh install working. I chronicle it here:
https://saricden.com/moralis-react-native-setup-december-2021-angry-debug-log

**Comment by jay-jlm** [comment]
Afaik, it should be possible by wrapping your app in a <WalletConnectProvider>, but I still get this error sometimes:

`[22:31:36] Non ethereum enabled browser`

...so I could use some official documentation on it.

**Comment by ErnoW** [comment]
It is correct that react-native will not work out-of-the box, without fixing dependencies.
That's why the best way to use it, is to use the boilerplate that you've suggested: https://github.com/ethereum-boilerplate/ethereum-react-native-boilerplate 
This is the boilerplate that is the best maintained and tested, and I would suggest using it as a starting point.

**Comment by ErnoW** [comment]
Closing this issue as it is rather an implementation issue. The recommended way to use react-native is to use https://github.com/ethereum-boilerplate/ethereum-react-native-boilerplate

Any questions or support can be asked in the forum as we are more active there with support and developers :)

**Comment by adamsr123** [comment]
expo is a great tool for working with react-native development, I think this should be addressed
