### ISSUE TITLE
Expose a method for signing messages (personal_sign)

### ISSUE THREAD

**Issue by aecorredor** [MoralisWeb3/react-moralis#117]
## New Feature Request

It'd be nice to have access to a method that lets users sign messages with the active provider. That way signing would work with metamask and with walletconnect.

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Cannot sign messages from a mobile device with walletconnect.

### Feature / Enhancement Description

By exposing a method to sign messages with the set provider mobile devices could support signing (with walletconnect).

### Example Use Case

I'm using rarible to build a dapp. They support unlockable NFT content, but the user's signature is needed. I currently get the signature using metamask and `window.ethereum.request` directly. Mobile devices don't have access to `window.ethereum`.

### Alternatives / Workarounds

Not sure if there is one for mobile devices.

### 3rd Party References

N/A

**Comment by ErnoW** [comment]
You have access to the web3 instance after you have called `authenticate` and/or `enableWeb3`. 

You can access this via `const { web3 } = useMoralis()` or via `Moralis.web3`

With this web3 instance you can do any web3 interaction that the web3.js library supports. For example `personal.sign` (https://web3js.readthedocs.io/en/v1.5.2/web3-eth-personal.html#sign).

If you have any further questions, please post it in https://forum.moralis.io/ as we have more people active there to check issues :)

**Comment by aecorredor** [comment]
@ErnoW cool! That's good to know. But, I did just try it and even thought we do have access to `personal.sign` through the moralis instance, it doesn't seem to use the `walletconnect` provider. For selling/minting it does work correctly, as I get directed to the metamask app as soon as I press on the buttons that call sell/mint. Any ideas what could be happening there? If not, I'll post something in the forum to keep track of it.
