### ISSUE TITLE
Error as "amount should be a number string"  with useOneInchSwap hook from react-moralis

### ISSUE THREAD

**Issue by ashish-pcode** [MoralisWeb3/react-moralis#145]
### Issue Description

Facing issue while using the useOneInchSwap hook from react-moralis

### Steps + code to reproduce

Params:
{
"chain": "bsc",
"fromTokenAddress": "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
"toTokenAddress": "0x55d398326f99059ff775485246999027b3197955",
"amount": "0.1",
"fromAddress": "0xc3cd0171dfdd36cb1d77efc07578b69252d65206",
"slippage": 1
}

Passing this object as param in "swap" function in "useOneInchSwap"

### Error

{
"statusCode": 400,
"error": "Bad Request",
"description": "amount should be a number string",
"meta": [
{
"type": "paramNumber",
"value": "amount"
}
],
"requestId": "be597da9-171e-4001-a38c-74285704d32f"
}

### Environment

Server

- Moralis server version:  0.0.302

Client

- react-moralis version: 0.3.11
- Moralis SDK version: 0.0.183
- Operating system: Mac OS
- Browser: Brave Browser

**Comment by ErnoW** [comment]
This should be solved by updating server to 0.0.330, see more details or questions on this issue in: https://forum.moralis.io/t/1nch-getquote-function-type-def-error-amount-should-be-a-number-string/4354/43
