### ISSUE TITLE
Authenticate Promise Return

### ISSUE THREAD

**Issue by maxmezzomo** [MoralisWeb3/react-moralis#155]
### Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [ x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

The React authenticate function returns a void promise `authenticate: (options?: AuthenticateOptions) => Promise<void>;`

### Feature / Enhancement Description

It would be nice to have a response to handle. Either for errors or anything else. In the the docs at https://docs.moralis.io/moralis-server/users/crypto-login#metamask it appears that there should be some response in the JS SDK although looking through the types it seems void as well (moralis/types/index.d.ts).

### Example Use Case

Any time you want to authenticate a user. Maybe catch errors.

### Alternatives / Workarounds

I think its probably fine for most use cases to just use the authError from the context. It just will not allow catching the error. In terms of development philosophy I dont actually know if it matters or not that the error fall through to console. Its probably better I'm not sure about that.

**Comment by ErnoW** [comment]
Will be added in next version (https://github.com/MoralisWeb3/react-moralis/pull/198)

Also, for error handling, you can specify `throwOnError` to handle the errors yourself. See https://github.com/MoralisWeb3/react-moralis#-error-handling
