### ISSUE TITLE
Currently you need `MORALIS_APPLICATION_ID` and `MORALIS_SERVER_ID` for nextjs 

### ISSUE THREAD

**Issue by PatrickAlphaC** [MoralisWeb3/react-moralis#156]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Right now, users _have_ to get an appId and ServerId to use moralis, it would be great if this wasn't the case. 

Steps to reproduce:

1. `npx create-next-app`
2. npm install react-moralis
3. Go to `_app.js` and make the file look like:

```js
import '../styles/globals.css'
import { MoralisProvider } from "react-moralis";

const moralisAppId = process.env.MORALIS_APPLICATION_ID || "xxxxxxxx"
const moralisServerId = process.env.MORALIS_SERVER_ID || "xxxxxxxx"

function MyApp({ Component, pageProps }) {
  return (
    <MoralisProvider appId={moralisAppId} serverUrl={moralisServerId}>
      <Component {...pageProps} />
    </MoralisProvider>
  )
}

export default MyApp
```

4. Run `npm run dev`

You'll get a wonderful error on the site after a refresh. However, if you add the appId and serverURL, this works fine. 

### Feature / Enhancement Description

The idea is to make it so that it can render ever without the appId and serverUrl, this way, someone could always use moralis even if they didn't make a server.

**Comment by web3developers** [comment]
+1

**Comment by ashish-pcode** [comment]
Same issue

**Comment by ErnoW** [comment]
@PatrickAlphaC  What we can do is add a boolean to `<MoralisProvider />`, called `initializeOnMount` that you can set to false. Then it will not initialize Moralis automatically. But it requires you to call an `initialise` function manually before you can use database specific actions, like `Moralis.User.current` or `Moralis.Query`.

It will limit functionalities, as a lot of functionalities depend on the `appId`.

**Comment by PatrickAlphaC** [comment]
Sounds awesome!

**Comment by ErnoW** [comment]
Implemented in v1.2.0, refer to https://github.com/MoralisWeb3/react-moralis#initialize for a guide on how to implement.

**Comment by PatrickAlphaC** [comment]
EXCITED TO TRY

**Comment by ErnoW** [comment]
Let me know what you think about it and if it works as expected 🤩

**Comment by PatrickAlphaC** [comment]
Been playing around with it for some time, and it's amazing!! Exactly what I was thinking.
