### ISSUE TITLE
Custom signing message not working

### ISSUE THREAD

**Issue by unsphere** [MoralisWeb3/react-moralis#16]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Using **authenticate({ signing: "Test" })** still shows "Moralis Authentication" on MetaMask.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Just try one of the examples and add **{ signing: "Test" }** to the authenticate function and you will notice that MetaMask still shows the default signing message.

**Comment by ErnoW** [comment]
> * **I'm submitting a ...**
>   [x] bug report
>   [ ] feature request
>   [ ] question about the decisions made in the repository
>   [ ] question about how to use this project
> * **Summary**
> 
> Using **authenticate({ signing: "Test" })** still shows "Moralis Authentication" on MetaMask.
> 
> * **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
> 
> Just try one of the examples and add **{ signing: "Test" }** to the authenticate function and you will notice that MetaMask still shows the default signing message.

There was an error in the documentation. It should be `signingMessage` instead of `signing`.

Just updated the docs. Thanks for reporting.

**Comment by unsphere** [comment]
ah, the classic one :) Thank you!
