### ISSUE TITLE
Types don't match the Moralis types

### ISSUE THREAD

**Issue by liron-navon** [MoralisWeb3/react-moralis#173]
### Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [ X] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ X] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

The types in react-moralis, don't match the types in [moralis sdk here](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/types/index.d.ts)

Which mean working with react moralis with typescript cause a lot of errors and cannot work properly.

### Steps + code to reproduce

1. import react moralis to a typescript project.
2. Tey to use "useMoralis" hook and call authenticate as shown in the instructions:

`authenticate({ provider: "walletconnect" })`

3. enjoy fighting the compilation errors, or converting everything into "any" =(

### Actual Outcome

Compilation errors, need to cast a lot of things to "any" to make it work.

### Expected Outcome

I would expect the types of react-moralis to match the types of moralis, and of the examples shown on the main README.md file to work with typescript

### Environment

Client

- react-moralis version: `v1.0.2`
- Moralis SDK version: `v1.0.3`
- Operating system: `osx`
- Browser: `chrome`

### Logs

<img width="567" alt="Screenshot 2022-01-20 at 19 59 14" src="https://user-images.githubusercontent.com/18119833/150404350-a17f8fc5-decb-4ca0-95ff-a7498c24ddf7.png">

**Comment by ErnoW** [comment]
This has recently be fixed. Please update to the latest version
