### ISSUE TITLE
underlying network changed when switch network

### ISSUE THREAD

**Issue by ChrisChan888** [MoralisWeb3/react-moralis#178]
### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [ ] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ ] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Environment

Server

- Moralis server version: `FILL_THIS_OUT`

Client

- react-moralis version: `^1.1.0`
- Moralis SDK version: `^1.1.0`
- Operating system: `mac`
- Browser: `chrome`

### Logs

Unhandled Rejection (Error): underlying network changed (event="changed", network={"chainId":43114,"name":"unknown"}, detectedNetwork={"chainId":43113,"name":"unknown"}, code=NETWORK_ERROR, version=providers/5.5.2)

**Comment by ChrisChan888** [comment]
How do I set “any” to MoralisWeb3Provider?
Like https://github.com/ethers-io/ethers.js/issues/866

**Comment by ErnoW** [comment]
This has recently be added., if you update to the latest version.

You now can provide `anyNetwork: true` as a param to the enableWeb3/authenticate call

Alternatively, also the web3 instance will be updated in react when the network changes. So you could implement a useEffect hook to update your contract for example.
