### ISSUE TITLE
Can't resolve 'magic-sdk' and '@walletconnect/web3-provider'

### ISSUE THREAD

**Issue by PatrickAlphaC** [MoralisWeb3/react-moralis#184]
## New Bug Report

WIth a new [nextjs](https://tailwindcss.com/docs/guides/nextjs) project, running `yarn dev` or `npm run dev` results in immediate warnings:

```
warn  - ./node_modules/moralis/lib/browser/Web3Connector/MagicWeb3Connector.js
Module not found: Can't resolve 'magic-sdk' in '/<project-path>/node_modules/moralis/lib/browser/Web3Connector'
```

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

```
yarn create next-app
yarn add moralis react-moralis
```

Then, update your `_app.js` file to look something like:

```
import { MoralisProvider } from "react-moralis"

function App({ Component, pageProps }) {
  return (
    <MoralisProvider initializeOnMount={false}>
      <Component {...pageProps} />
    </MoralisProvider>
  )
}

export default App
```
Then run:

```
yarn dev
```

And you'll see the warnings. If you go ahead and add that package, you then get it complaining about not finding `@walletconnect/web3-provider`

### Actual Outcome

```
warn  - ./node_modules/moralis/lib/browser/Web3Connector/MagicWeb3Connector.js
Module not found: Can't resolve 'magic-sdk' in '/<project-path>/node_modules/moralis/lib/browser/Web3Connector'
```

### Expected Outcome

No warnings

### Environment

```
    "moralis": "^1.2.3",
    "next": "12.0.9",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-moralis": "^1.2.1"
```
macos Monterey 12.1
yarn: 1.22.17

Server - N/A

**Comment by malithmcr** [comment]
I also had the same warning and you need to manually install these dependencies:

```
yarn addd magic-sdk
@walletconnect/web3-provider
yarn add moralis
```

then the error goes away.  Maybe its because of these packages are in the devDependency of react-moralis. Hopefully this will be fixed in the future.

**Comment by ErnoW** [comment]
These dependencies are optional dependencies, so if you don't need them, then you don't have to install them.

The warning messages have been filtered out in a recent release.

**Comment by yungobiwan** [comment]
I'm using  "moralis": "^1.3.1" and  "react-moralis": "^1.3.0" but it is still throwing those dependency errors and crashes a nextJS project

**Comment by ErnoW** [comment]
> I'm using "moralis": "^1.3.1" and "react-moralis": "^1.3.0" but it is still throwing those dependency errors and crashes a nextJS project

The fact that the app crashes, might be because of another error, please check if you have other errors and if the same thing happens with a clean/new project

**Comment by yungobiwan** [comment]
@ErnoW Actually you are right it does not crash the nextJS server. Sorry fo the false alarm 
:sweat_smile:

**Comment by overgrowninfnat** [comment]
Since these are optional dependencies and these warnings comes from Webpack 5 (in Next.js v. 12 the support for Webpack 4 was removed) I've got rid of them by customising webpack config in next.config.js as follow:

```
module.exports = {
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
      config.ignoreWarnings = [
        {
          message: /(magic-sdk|@walletconnect\/web3-provider|@web3auth\/web3auth)/,
        }
        
      ]
      return config
    },
  }
```

**Comment by Kipitup** [comment]
Hello,

I also have this issue, but I'm not using NextJS, only classic React.

**Comment by acushlakoncept** [comment]
This solved the issue for me on Next.js
`yarn add magic-sdk  @walletconnect/web3-provider  @web3auth/web3auth`

**Comment by Birdland998** [comment]
install the xcode
