### ISSUE TITLE
Add web3modal compatibility 

### ISSUE THREAD

**Issue by PatrickAlphaC** [MoralisWeb3/react-moralis#185]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Right now, the suggested way for users to authenticate is to click a button for either wallet connect or metamask, however it would be great if the default was just "connect" and it brought you to a screen where you could pick your connection, like [web3modal has](https://github.com/Web3Modal/web3modal). 

I think it would be great to integrate this plugin out of the box. 

I'm not sure if this belongs here or in the main moralis SDK package

**Comment by ivan-liljeqvist** [comment]
thats a great idea, will forward to the team now

**Comment by PatrickAlphaC** [comment]
I should have clarified.

I meant it would be great to have an `"import {moralisModal} from "useMoralis"`, so that users wouldn't need to go through the laborious process of adding all the possible connections. 

Then, they could do like `moralisModal.connect` and the user could pick whatever the developers have designed in the config. Giving the choice to the developer of having them connect to "raw" metamask, walletconnect etc, or "authenticated" metamask, walletconnect, etc.

"Raw" meaning without a moralis server
"Authenticated" of course having a moralis server.

**Comment by locothedev** [comment]
@ivan-liljeqvist @PatrickAlphaC this sounds like something perfect for [web3uikit](https://github.com/web3ui/web3uikit)
👀

**Comment by Y0moo** [comment]
I'm working now on `<ConnectButton />` for [web3uikit](https://github.com/web3ui/web3uikit) and it will have similar functionality.

**Comment by PatrickAlphaC** [comment]
oooooooooo

**Comment by ErnoW** [comment]
I agree, this is perfect for web3Ui kit, closing this issue
