### ISSUE TITLE
Can't get NFTBalance when refresh the page

### ISSUE THREAD

**Issue by best-lucky1030** [MoralisWeb3/react-moralis#191]
I am using `react-moralis` and version is `^1.2.2`.
Using `useNFTBalances`, I am getting data like this format:

```
{
  "total": 1,
  "page": 0,
  "page_size": 500,
  "result": [
    {
      "token_address": "0x686c626E48bfC5DC98a30a9992897766fed4Abd3",
      "token_id": "15",
      "contract_type": "ERC721",
      "owner_of": "0x686c626E48bfC5DC98a30a9992897766fed4Abd3",
      "block_number": "88256",
      "block_number_minted": "88256",
      "token_uri": "string",
      "metadata": "string",
      "synced_at": "string",
      "amount": "1",
      "name": "CryptoKitties",
      "symbol": "RARI"
    }
  ]
}
```

Btw, when I refresh the browser or click `Refetch NFTBalances` button, it shows null.
But when I log out and sign in again, it works again.

**Comment by ErnoW** [comment]
You might need to call `Moralis.enableWeb3()`.

Every time when you refresh the app, you will need to connect to the blockchain again (via metamask/walletconnect etc.)
