### ISSUE TITLE
URL at bottom of README is broken

### ISSUE THREAD

**Issue by PatrickAlphaC** [MoralisWeb3/react-moralis#196]
### Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x ] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ x] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

https://github.com/MoralisWeb3/demo-apps/tree/main/react-moralis-examples << Look at the bottom of the readme. This URL is not accessible by me.

**Comment by ErnoW** [comment]
Thanks, it's updated now

**Comment by PatrickAlphaC** [comment]
I still get github telling me the page doesn't exist?

**Comment by ErnoW** [comment]
Correct, those examples are outdated. That's why we now link to the boilerplate project, which is a good example to reference to: https://github.com/ethereum-boilerplate/ethereum-boilerplate
