### ISSUE TITLE
Bug: web3auth

### ISSUE THREAD

**Issue by EricForgy** [MoralisWeb3/react-moralis#206]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

react-moralis v1.3.1 cannot use web3auth via `useMoralis`.

It looks like `AuthenticateOptions` is missing `clientId` in `useMoralis.ts`:

https://github.com/MoralisWeb3/react-moralis/blob/main/src/hooks/core/useMoralis/_useMoralisAuth.ts#L47-L58

### Feature / Enhancement Description

Add `clientId` to `AuthenticateOptions` in `useMoralis.ts`.

**Comment by ErnoW** [comment]
moralis is a peer dependency of react-moralis.
So you need to update to the latest version of moralis in your package. Then it should work

**Comment by EricForgy** [comment]
Hi @ErnoW 👋 

Thanks for the quick response 👍 

In my dapp, I am using moralis v1.3.2 and react-moralis v1.3.1.

Maybe I am confused, but this

https://github.com/MoralisWeb3/react-moralis/blob/main/package.json#L67

looks like it is forcing moralis v1.1.0 🤔

**Comment by EricForgy** [comment]
Hmm... it looks like I do have moralis v1.3.2 in my node_modules 🤔 

It must be some other reason why I am getting that error with `AuthenticateOptions` 🤔

**Comment by EricForgy** [comment]
It looks like there needs to be a `clientId` here maybe?

https://github.com/MoralisWeb3/react-moralis/blob/main/src/hooks/core/useMoralis/_useMoralisAuth.ts#L47-L58

**Comment by EricForgy** [comment]
> It looks like there needs to be a `clientId` here maybe?
> 
> https://github.com/MoralisWeb3/react-moralis/blob/main/src/hooks/core/useMoralis/_useMoralisAuth.ts#L47-L58

Yep. I think this is the problem and updated the issue description accordingly 👍 🙏

**Comment by EricForgy** [comment]
Bump 👋 

Any thoughts on this? It's be great to be able to try out web3auth with react-moralis 🙏

**Comment by ErnoW** [comment]
Fixed in the latest version.
Make sure to update both `react-moralis` and `moralis`

**Comment by EricForgy** [comment]
Hi 👋 

We might need to reopen this issue. I finally got around to giving web3auth a try and it doesn't seem to be working for me:

```
    if (!isAuthenticated) {
        return (
            <div>
                <ButtonComponent onClick={() => authenticate(
                    {
                        provider: "web3Auth",
                        clientId
                    }
                )}>Connect Wallet</ButtonComponent>
            </div>
        );
    }
```

At least I can run it now, but nothing happens. No error. No output to the console. If I don't include the options, it works as usual.

It could be I'm doing something else wrong though.

**Comment by popisdead** [comment]
bump
