### ISSUE TITLE
React Moralis not working with Vite Built React App

### ISSUE THREAD

**Issue by djimenezdev** [MoralisWeb3/react-moralis#210]
Hello! So I have built my react app using vite rather than create react app. I installed react-moralis via yarn and I imported the MoralisProvider Component into my main.jsx and wrapped the App component as seen below:

![react-moralis-1](https://user-images.githubusercontent.com/42664403/155895626-bc39bb66-dde2-4367-b4a4-214774eb7366.png)

And when I run the app I get this issue:

![react-moralis-2](https://user-images.githubusercontent.com/42664403/155895671-bda941f5-9bd4-476f-98c4-fe012c0f59e6.png)

I was confused about this until I read that I needed to have the moralis pacakage installed as react-moralis requires it as a dependency so I installed moralis via yarn and thought that would fix the issue until I got this error in the console:

![react-moralis-3](https://user-images.githubusercontent.com/42664403/155895849-53e4332c-e915-40af-848f-968ec75b2956.png)

Would anyone happen to know how I could go about fixing this issue? 

Thanks for the help!

**Comment by ErnoW** [comment]
Hmm, seems to be an issue with how Vite is handleing ES6 modules.
I saw this post (https://community.parseplatform.org/t/vue-vite-parse-js-error-super-expression-must-either-be-null-or-a-function/2001), a similar error on Parse (Moralis bootstrapped from Parse, so this is likely the same error)

We have little experience in Vite, and need to check if this is an issue that we can solve, or if it is a configuration of Vite for example.

**Comment by ErnoW** [comment]
Possibly related to: https://github.com/MoralisWeb3/Moralis-JS-SDK/issues/271

**Comment by overgrowninfnat** [comment]
This type of error commonly comes out from wrong import or circular dependencies, and, as shown in the attached svg graph generated by the madge package, this SDK has 55 circular dependencies. Hopes it can help ;)

![graph](https://user-images.githubusercontent.com/17546550/156903927-2e3ba19e-bcd0-4814-856e-b1dc983087d0.svg)

**Comment by djimenezdev** [comment]
No worries! thank you so much reading through the links you sent me helped me figure out how to get it working in development and production. I appreciate the help!
