### ISSUE TITLE
MoralisProvider children

### ISSUE THREAD

**Issue by 7flash** [MoralisWeb3/react-moralis#215]
https://github.com/MoralisWeb3/react-moralis/blob/6c5e4f0572973a9637f6ea69ba26ca4c4e92776b/src/context/MoralisProvider/MoralisProvider.tsx#L21

It expects to have **children** parameter - what should I pass?

**Comment by ErnoW** [comment]
It should look something like this:
```
<MoralisProvider>
   <YourApp />
</MoralisProvider>
```

Please see the docs for examples: https://github.com/MoralisWeb3/react-moralis#readme

And make sure you understand react concepts: https://reactjs.org/docs
