### ISSUE TITLE
BUG: account is always lower case

### ISSUE THREAD

**Issue by anarkrypto** [MoralisWeb3/react-moralis#231]
### Issue Description

Ethereum addresses are case sensitive.

However when getting the account from useMoralis, I noticed that it is always lower case.

So when trying to compare, verify signatures and etc, the result is always false.

#### Example:
0x52439d1a5bcad8757b8de46ae4bd93bc247dba0d is **NOT** 0x52439d1A5BCaD8757B8De46AE4BD93Bc247dBA0d

#### Specific
```js
const { account } = useMoralis()
```

#### Complete
```js
import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import { MoralisProvider, useMoralis } from "react-moralis";

function App() {
  const { account, enableWeb3 } = useMoralis();
  useEffect(() => {
    enableWeb3({
      provider: "metamask",
      chainId: 1,
      onSuccess: (res) => console.info("Success!", res),
      onError: (err) => alert(JSON.stringify(err)),
      throwOnError: true
    });
  }, []);
  return <div>Account: {account}</div>;
}

ReactDOM.render(
  <MoralisProvider initializeOnMount={false}>
    <App />
  </MoralisProvider>,
  document.getElementById("container")
);
```

Demo: [https://codesandbox.io/s/react-playground-forked-oj22cq](https://codesandbox.io/s/react-playground-forked-oj22cq?file=/index.js:0-674)

### Softwares / dependencies version:

Node.js: v16.13.1
React: 17.0.2,
react-moralis: ^1.3.5
Ubuntu 20.04.3 LTS

**Comment by Qudusayo** [comment]
Ethereum addresses are displayed in HEX, so they are not case-sensitive. You could capitalize or lower-case any of the letters, and the address is still the same since A and a are the same in HEX.

What you're doing is a Javascript check, you can lowercase both addresses to check if they're the same rather, not an issue with react-moralis.

**Comment by EricForgy** [comment]
Just to add... the docs state that this behavior is intentional and suggest always lowercasing your addresses before comparing 👍

**Comment by anarkrypto** [comment]
Answered. I'm used to base58, I didn't realize that eth addresses are hex. I can fix converting always to lower case so. Thanks, closing it.
