### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by JimLynchCodes** [MoralisWeb3/react-moralis#248]
Docs are confusing af.

Why examples only show "authentication" and that's it? I don't even care about authentication.

Please add example of calling an API. this lib is super broken

**Comment by locothedev** [comment]
Please check the readme again. Especially the **Usage** part there are lots of examples :)

What is broken for you?

**Comment by ivan-liljeqvist** [comment]
@JimLynchCodes use respectful language no one will help you with this tone 

if you need help - post in https://forum.moralis.io

**Comment by JimLynchCodes** [comment]
well, idk I guess but seven ocho there
