### ISSUE TITLE
Cannot find module: 'moralis' while Netlify deploy

### ISSUE THREAD

**Issue by happylolonly** [MoralisWeb3/react-moralis#5]
- **I'm submitting a ...**
  [x] bug report
  [x] feature request

Hi, I am trying to deploy the app to Netlify, but it shows error:
```
1:23:45 PM: > react-scripts build
1:23:47 PM: Creating an optimized production build...
1:23:53 PM: Failed to compile.
1:23:53 PM: 
1:23:53 PM: ./node_modules/react-moralis/lib/index.esm.js
1:23:53 PM: Cannot find module: 'moralis'. Make sure this package is installed.
```

I will install `moralis` to my project now, but it is possible to fix it for new users?

![image](https://user-images.githubusercontent.com/18665326/125436507-737add56-595d-4e8f-aafc-d372984b47d5.png)

**Comment by ErnoW** [comment]
> * **I'm submitting a ...**
>   [x] bug report
>   [x] feature request
> 
> Hi, I am trying to deploy the app to Netlify, but it shows error:
> 
> ```
> 1:23:45 PM: > react-scripts build
> 1:23:47 PM: Creating an optimized production build...
> 1:23:53 PM: Failed to compile.
> 1:23:53 PM: 
> 1:23:53 PM: ./node_modules/react-moralis/lib/index.esm.js
> 1:23:53 PM: Cannot find module: 'moralis'. Make sure this package is installed.
> ```
> 
> I will install `moralis` to my project now, but it is possible to fix it for new users?
> 
> ![image](https://user-images.githubusercontent.com/18665326/125436507-737add56-595d-4e8f-aafc-d372984b47d5.png)

This package requires `react`, `react-dom` and `moralis` to be installed dependencies (to keep the bundle-size of this package small). Please let me know if you still have issues after adding the dependencies.

**Comment by happylolonly** [comment]
No, it worked.
But maybe then need to update instructions? Usually, people copy, and locally it worked without `moralis` install.

![image](https://user-images.githubusercontent.com/18665326/125623121-3a6aea31-27ee-4574-8043-bcc7f9144d49.png)
