### ISSUE TITLE
How to use Moralis.Web3.getNFTs() with this library

### ISSUE THREAD

**Issue by newbreedofgeek** [MoralisWeb3/react-moralis#6]
- **I'm submitting a ...**
question about how to use this project

- **Summary**
How do I use the Moralis.Web3 methods like `Moralis.Web3.getNFTs();` as shown here - https://docs.moralis.io/transactions-and-balances/nft-balances

Documentation says `web3 | The web3 instance of Moralis.Web3;` will do it....

but bringing in via:

`const { web3 } = useMoralis()`

does not seem to have these methods like getNFTs as I get an undefined error.

i.e. `web3.getNFTs()` --> undefined

**Comment by ivan-liljeqvist** [comment]
our team monitors questions like this on https://forum.moralis.io, please post there and we will get back asap

**Comment by newbreedofgeek** [comment]
for future reference for anyone else - this has been answered here - https://forum.moralis.io/t/getnfts-not-working-with-react-moralis/997
