### ISSUE TITLE
console warn after initially start react-moralis

### ISSUE THREAD

**Issue by dohomi** [MoralisWeb3/react-moralis#82]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

The current version produces this console warn inside of the console:

```
Moralis.enable() is deprecated and will be removed, use Moralis.enableWeb3() instead.

Module not found: Can't resolve '@walletconnect/web3-provider'
````

### Steps + code to reproduce
Just install and start react-moralis. It seems that an outdated method been called inside of the MoralisProvider

I am not using walletconnect (I use Metamask) but I still see the warning about walletconnect/web3-provider. There might be a way to hide the warning in case its not being used?

**Comment by ErnoW** [comment]
The first warning is fixed now.
We still need to find a solution for the walletconnect warning. This happens because it is an optional dependency. We still need to find a better way to implement this without triggering a warning. For now, you can ignore this warning when you're not using walletconect.

**Comment by ErnoW** [comment]
Both warnings have been solved if you use the latest version of moralis and react-moralis
