### ISSUE TITLE
How to catch an EVM/Transaction error correctly

### ISSUE THREAD

**Issue by dohomi** [MoralisWeb3/react-moralis#83]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

If an EVM error is being thrown if the user communicates with a contract through MetaMask then inside of NextJS the error is not being captured.

Is there any way to have a proper async error handling in place? 

### Feature / Enhancement Description

Add possibility to watch for errors of web3.ether.contract. The Transaction error is correct but I could not find a way how to handle the error.
<img width="720" alt="Screenshot 2021-11-13 at 00 33 48" src="https://user-images.githubusercontent.com/489221/141501645-488d9a7b-e223-4bcd-8a0b-2f7c31a4cf8a.png">

**Comment by dohomi** [comment]
Currently I am using following block to solve it, first I use `.call` and that seems to be catched correctly. `.send` does not seem to be able to show the error correctly  :
```js
try{
  await contract.methods.mint(selectedAmount)
                    .call({ value: contractDescription.getCurrentCost }) 
  await contract.methods.mint(selectedAmount)
                    .send({ value: contractDescription.getCurrentCost })
} catch(e){
  console.log("error is thrown while trying to ming..", e)
}
```

**Comment by ErnoW** [comment]
This is how web3.js works. The send call is successfully sent, but you will need to wait until it is confirmed or rejected. Check the docs from web3.js on how to do this properly: https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-send 

Will close this issue as it is related to web3.js, not react-moralis
