### ISSUE TITLE
Error of react-moralis in ReactNative 0.66.3?

### ISSUE THREAD

**Issue by nyousaf47** [MoralisWeb3/react-moralis#94]
### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description
I am getting this error on latest ReactNative version.
`TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter")`

### Steps + code to reproduce

Just create a new Project using cli commands
Install `react-moralis` 
Run the app, you will get above error.

### Actual Outcome

It gives error of EventEmitter file.

**Comment by saricden** [comment]
Same issue as: https://github.com/MoralisWeb3/react-moralis/issues/112 I'm pretty sure.

**Comment by ErnoW** [comment]
Closing this issue as it is rather an implementation issue. The recommended way to use react-native is to use https://github.com/ethereum-boilerplate/ethereum-react-native-boilerplate

Any questions or support can be asked in the forum as we are more active there with support and developers :)
